name: Deploy to Both Private EC2 Instances

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH Key & known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

    - name: Upload code to Bastion (rsync)
      run: |
        rsync -az --delete \
          -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
          --exclude ".git" \
          --exclude ".github" \
          ./ \
          ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}:~/app/

    - name: Deploy to Private EC2 Instances via Bastion (rsync)
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} << 'EOF'
          for node in ${{ secrets.EC2_NODE_1 }} ${{ secrets.EC2_NODE_2 }}; do
            rsync -az --delete \
              -e "ssh -o StrictHostKeyChecking=no" \
              ~/app/ ec2-user@"$node":/home/ec2-user/app/

            ssh -o StrictHostKeyChecking=no ec2-user@"$node" "
              sudo mkdir -p /var/www/html &&
              sudo rsync -az --delete /home/ec2-user/app/ /var/www/html/ &&
              (sudo systemctl restart nginx || sudo systemctl restart httpd)
            "
          done
          EOF
